//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reg.dcom.driver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reg.dcom.driver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bui
        ///Mai
        ///Mac
        ///Hua
        ///Dong
        ///Phung
        ///Cao 
        ///Huynh
        ///Truong
        ///Vu
        ///Luong
        ///Nguyen
        ///Quoc
        ///Le
        ///Tran
        ///Duong
        ///Nguyen
        ///Nguyen
        ///Van
        ///Tran
        ///Thi
        ///Nguyen
        ///Danh
        ///Nguyen
        ///Tran
        ///Phan Le.
        /// </summary>
        internal static string ho {
            get {
                return ResourceManager.GetString("ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quynh
        ///Thanh
        ///Cong
        ///Duong
        ///Hai
        ///Luan
        ///Tien
        ///Manh
        ///Luc
        ///Phi
        ///Toan
        ///Kien
        ///Mai
        ///Hao
        ///Giang
        ///Huy
        ///Duy
        ///May
        ///Quyet
        ///Khanh
        ///Linh
        ///Thao
        ///Diep
        ///Long
        ///Hung
        ///Manh
        ///Hai
        ///Tung
        ///Quang
        ///Linh
        ///Trang
        ///Van
        ///Kien
        ///Tuan
        ///Anh
        ///Ha
        ///Hoc
        ///Nam
        ///Tam
        ///Bac
        ///Xuan
        ///Kinh
        ///Hoang
        ///Hau
        ///Tap
        ///Thu
        ///Hoan
        ///Hanh
        ///Tam
        ///Hien
        ///Kha
        ///Phong
        ///Phuoc
        ///Cong
        ///Man
        ///Duc
        ///Nguyen
        ///Nhat
        ///Nhut
        ///Hoang
        ///Diep
        ///Ngoc
        ///Minh
        ///Thieu
        ///Khai
        ///Dat
        ///Quynh
        ///Thanh
        ///Giang
        ///Thao
        ///Diep
        ///Yen
        ///Trang
        ///Huyen
        ///Nga
        ///Huong
        ///Lan
        ///My
        ///Hau
        ///Loan
        ///Hien
        ///Diep
        ///Minh
        ///Oanh
        ///Mai
        ///Loan
        ///Linh
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
    }
}
